version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - MSSQL_USER=sa
      - MSSQL_PASSWORD=P@ssw0rd123!  # Set a strong password
      - MSSQL_DATABASE=HotelDemo     # Initial database name
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped 

volumes:
  sqlserver_data:
