version: "3"

services:
  booking-postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=booking
      - POSTGRES_PASSWORD=booking
      - POSTGRES_DB=booking
